site_name: Acceso a Datos DAM
site_url: https://jmabadlopez.github.io/acceso_datos/site/

nav:
  - Inicio: index.md
  - Unidades:
    - UD1 - Programación en el entorno Kotlin.: unidades/ud01/ud01.md
    - UD2 - Persistencia en ficheros:
      - Introducción: unidades/ud02/introduccion.md
      - Ficheros y directorios: unidades/ud02/ficheros_directorios.md
      - Ficheros de texto: unidades/ud02/ficheros_texto.md
      - Ficheros de intercambio: unidades/ud02/ficheros_intercambio.md
      - Ficheros binarios: unidades/ud02/ficheros_binarios.md
      - Ficheros de acceso aleatorio: unidades/ud02/ficheros_acceso_aleatorio.md
      - Entrega y documentación final: unidades/ud02/documentacion_final.md
    - UD3 - Persistencia en Bases de Datos:
      - Introducción: unidades/ud03/introduccion.md
      - Conexiones: unidades/ud03/conexiones.md
      - Operaciones: unidades/ud03/operaciones.md
      - Arquitectura de Acceso a Datos (Patrón DAO): unidades/ud03/dao.md
      - Transacciones: unidades/ud03/transacciones.md
      - Migración del SGBD: unidades/ud03/migracion.md
      - Documentación y entrega final: unidades/ud03/entrega.md
    # - UD4 - Mapeo Objeto Relacional (ORM):
      # - Introducción: unidades/ud04/introduccion.md

repo_url: https://github.com/jmabadlopez/acceso_datos
repo_name: jmabadlopez/acceso_datos

theme:
  name: material
  language: es
  logo: ./assets/images/camp.png
  favicon: ./assets/images/camp.png
  icon: fontawesome/brands/mastodon
  hljs_languages:
    - python
    - java
    - c
    - kotlin
  features:
    - navigation.top
    - optimize
    - content.code.copy
    - navigation.footer
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Modo oscuro
      primary: orange
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro
      primary: orange
      accent: orange
markdown_extensions:
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition


# plugins:
#   - to-pdf:
#       author: José Manuel Abad López
#       copyright: 🄯 Creative Commons CC BY-SA 4.0 2025
#       cover_title: Acceso a Datos
#       cover_subtitle: 2º DAM
#       toc_title: "Contenidos"
#       toc_level: 3
#       output_path: ../public/libro.pdf