site_name: Acceso a Datos DAM
site_url: https://jmabadlopez.github.io/acceso_datos/site/

nav:
  - Unidades:
    - UD1 - Programación en el entorno Kotlin.: unidades/ud01/ud01.md
    - UD2 - Persistencia en ficheros:
      - Introducción: unidades/ud02/introduccion.md
      - Ficheros y directorios: unidades/ud02/ficheros_directorios.md
      - Ficheros de texto: unidades/ud02/ficheros_texto.md
      - Ficheros de intercambio: unidades/ud02/ficheros_intercambio.md
      - Ficheros binarios: unidades/ud02/ficheros_binarios.md
      - Ficheros de acceso aleatorio: unidades/ud02/ficheros_acceso_aleatorio.md
      - Entrega y documentación final: unidades/ud02/documentacion_final.md
    - UD3 - Persistencia en Bases de Datos:
      - Introducción: unidades/ud03/introduccion.md
      - Conexiones: unidades/ud03/conexiones.md
      - Operaciones: unidades/ud03/operaciones.md
      - Arquitectura de Acceso a Datos (Patrón DAO): unidades/ud03/dao.md
      - Transacciones: unidades/ud03/transacciones.md
      - Migración del SGBD: unidades/ud03/migracion.md
      - Entrega y documentación final: unidades/ud03/entrega.md
    - UD4 - ORM. Mapeo Objeto Relacional:
      - Introducción: unidades/ud04/introduccion.md
      - Creación de esquemas de BD: unidades/ud04/tablas.md
      - CRUD Básico y Persistencia: unidades/ud04/operaciones.md
      - Consultas avanzadas con un ORM: unidades/ud04/consultas.md
    - UD5 - Diseño de componentes. API REST:
      - Introducción: unidades/ud05/introduccion.md
      - Configuración del entorno y persistencia: unidades/ud05/configuracion_persistencia.md
      - Capa de dominio y de servicio: unidades/ud05/servicio.md
      - Rutas. Implementación del CRUD completo: unidades/ud05/rutas.md
      - Autenticación y Sesiones: unidades/ud05/autenticacion_sesiones.md
      - Arquitectura y despliegue: unidades/ud05/despliegue.md
      - 💡Proyecto Final: unidades/proyecto/proyecto.md
  - Presentación: index.md

repo_url: https://github.com/jmabadlopez/acceso_datos
repo_name: jmabadlopez/acceso_datos


theme:
  name: material
  language: es
  logo: ./assets/images/camp.png
  favicon: ./assets/images/camp.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  font: 
    code: Roboto Mono
  hljs_languages:
    - python
    - java
    - c
  features:
    - optimize
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Modo oscuro
      primary: orange
      accent: orange 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro
      primary: orange
      accent: orange
markdown_extensions:
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/jmabadlopez/acceso_datos